app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__ , template_folder='templates')

from app.main import routes

app/main/routes.py
from app import create_app, db
from sqlalchemy import exc,asc, desc, and_, or_
import datetime
from app.main import main
from flask import session
import requests
# from app.auth import authentication as at
from flask_login import login_required
from flask_login import login_user, logout_user, login_required, current_user
from flask import render_template, request, redirect, url_for, flash, jsonify # for flash messaging
from app.main.models import TASK, WORKER, MESSAGE, SURVEY, TIME_SPENT

from app.main.forms import CreateNewProject, surveys, EditProject


#http://127.0.0.1:5000/bot?context=stress&q=1&c=1&d=2

#https://stackoverflow.com/questions/8551952/how-to-get-last-record

@main.route('/')
def home():
    return render_template("home.html")

@main.route('/list_tasks')
def list_tasks():
    return render_template("list-tasks.html", tasks = TASK.query.order_by(asc(TASK.id)).all(), \
    count = db.session.query(TASK).count())


@main.route('/setTime', methods=['GET', 'POST'])
def setTime():
    # print("i got you")
    session['start_time'] = datetime.datetime.utcnow()
    # print(session['start_time'])
    return jsonify(123)

@main.route('/bot', methods=['GET', 'POST'])
def bot():
    if request.method == 'POST':
        data = request.get_json()
        print(data['message'])

        if 'start_time' not in session:
            start_time = datetime.datetime.min
        else:
            start_time = session['start_time']

        message = MESSAGE(data['question'], data['message'], int(data['workerId']), int(data['task_id']),\
                          start_time, datetime.datetime.utcnow())

        db.session.add(message)
        db.session.commit()
        session.pop('start_time', None)

        return jsonify(123)
    if request.method == 'GET':
        context = request.args.get('context')
        complexity = request.args.get('c')
        return render_template("bot.html", context=context, complexity=complexity)

@main.route('/consent', methods=['GET', 'POST'])
def consent():
    if request.method == 'POST' and request.args.get('context') == "stress":
        #get the ID of the task
        task_id = getTaskID(request.args.get('context'), request.args.get('c'), \
                            request.args.get('q'), request.args.get('d'), request.args.get('ft'))

        #add worker in the DB
        w_id = addWorker(request.form.get('workerId'))

        return redirect(url_for('main.stress_task', workerId = w_id, task_id = task_id, context=request.args.get('context'), \
        c = request.args.get('c'), q=request.args.get('q'), d=request.args.get('d'), ft=request.args.get('ft'), mood = request.form.get('PAM')))

    if request.method == 'POST' and request.args.get('context') == "IR":
        #get the ID of the task
        task_id = getTaskID(request.args.get('context'), request.args.get('c'), \
                            request.args.get('q'), request.args.get('d'), request.args.get('ft'))

        #add worker in the DB
        w_id = addWorker(request.form.get('workerId'))
        return redirect(url_for('main.IR_task', workerId = w_id, task_id = task_id, context=request.args.get('context'), \
        c = request.args.get('c'), q=request.args.get('q'), d=request.args.get('d'), ft=request.args.get('ft'), mood = request.form.get('PAM')))

    if request.method == 'GET':
        return render_template("consent-form.html")



@main.route('/stress_task', methods=['GET', 'POST'])
def stress_task():
    if request.method == 'POST':
        time_spent = TIME_SPENT("stress_inst", int(request.args.get('workerId')), int(request.args.get('task_id')), \
                                session['start_time'], datetime.datetime.utcnow())
        db.session.add(time_spent)
        db.session.commit()
        session.pop('start_time', None)

        return redirect(url_for('main.bot', workerId = request.args.get('workerId'), task_id = request.args.get('task_id'), context=request.args.get('context'), \
        c = request.args.get('c'), q=request.args.get('q'), d=request.args.get('d'), ft=request.args.get('ft'), mood = request.args.get('mood')))
    if request.method == 'GET':
        return render_template("stress-task.html")

@main.route('/IR_task', methods=['GET', 'POST'])
def IR_task():
    if request.method == 'POST':
        time_spent = TIME_SPENT("IR_inst", int(request.args.get('workerId')), int(request.args.get('task_id')), \
                                session['start_time'], datetime.datetime.utcnow())
        db.session.add(time_spent)
        db.session.commit()
        session.pop('start_time', None)

        return redirect(url_for('main.bot', workerId = request.args.get('workerId'), task_id = request.args.get('task_id'), context=request.args.get('context'), \
        c = request.args.get('c'), q=request.args.get('q'), d=request.args.get('d'), ft=request.args.get('ft'), mood = request.args.get('mood')))
    if request.method == 'GET':
        return render_template("IR-task.html")

@main.route('/thankyou', methods=['GET', 'POST'])
def thankyou():
    task = TASK.query.filter_by(id = int(request.args.get('task_id'))).first()
    return render_template("thankyou.html", completion_url = task.URL_completion_code)


@main.route('/exit_surveys', methods=['GET', 'POST'])
def exit_surveys():

    form = surveys(meta={'csrf': False})

    if form.validate_on_submit():
        print("I am talking from exit surveys")

        s = SURVEY(int(request.args.get('workerId')),\
                   int(request.args.get('task_id')),\
                   request.args.get('mood'),\
               request.form['Perceived_waiting_time'],\
               request.form['cognitive'],\
               request.form['irritation'],\
               request.form['fairness'],\
               request.form['annoyance'],\
               request.form['boredom'],\
               request.form['stress'],\

               request.form['FI1'],\
               request.form['FI2'],\
               request.form['FI3'],\
               request.form['FI4'],\

               request.form['TD1'],\
               request.form['TD2'],\
               request.form['TD3'],\
               request.form['TD4'],\
               request.form['TD5'],\

               request.form['HE1'],\
               request.form['HE2'],\
               request.form['HE3'],\
               request.form['HE4'],\

               request.form['CO1'],\
               request.form['CO2'],\
               request.form['CO3'],\

               request.form['CU1'],\
               request.form['CU2'],\
               request.form['CU3'],\

               request.form['PU1'],\
               request.form['PU2'],\
               request.form['PU3'],\
               request.form['PU4'],\

               request.form['UEQ1'],\
               request.form['UEQ2'],\
               request.form['UEQ3'],\
               request.form['UEQ4'],\
               request.form['UEQ5'],\
               request.form['UEQ6'],\
               request.form['UEQ7'],\
               request.form['UEQ8'],\


               request.form['satisfaction'],\

               request.form['feedback'],\

               request.form['exp1'],\
               request.form['exp2'],\

               request.form['social_o_1'],\
               request.form['social_o_2'],\

               request.form['education'])
        db.session.add(s)
        db.session.commit()

        #store time spent in conv.task in DB
        fillBotTimeSpent(int(request.args.get('workerId')),\
                         int(request.args.get('task_id')),\
                         request.args.get('context'))
        # workerId = request.args.get('workerId'), task_id = request.args.get('task_id'), context=request.args.get('context'), \
        # c = request.args.get('c'), q=request.args.get('q'), d=request.args.get('d'), ft=request.args.get('ft'), mood = request.args.get('mood')
        return redirect(url_for('main.thankyou', workerId = request.args.get('workerId'), task_id = request.args.get('task_id'), context=request.args.get('context'), \
        c = request.args.get('c'), q=request.args.get('q'), d=request.args.get('d'), ft=request.args.get('ft'), mood = request.args.get('mood')))
    #if request ids GET
    context = request.args.get('context')
    if context == "stress":
        botname = "Ustad"
    else:
        botname = "Talash"
    return render_template("exit-surveys.html", form=form, botname=botname)

        # form.example.dat
        # print(request.form['social_o_1'], request.form['social_o_1'])




@main.route('/prolific_admin',  methods=['GET', 'POST'])
@login_required
def prolific_admin():

    form = CreateNewProject(meta={'csrf': False})

    if form.validate_on_submit():
        if db.session.query(TASK).filter(and_(TASK.context == form.context.data, TASK.complexity == form.complexity.data, \
        TASK.quality == form.quality.data, TASK.delay == form.delay.data, TASK.filler_type == form.filler.data)).count() == 1:
            flash('Sorry this task already exists in the database!')
            return redirect(url_for('main.prolific_admin'))
        else:
            t = TASK(form.title.data, form.context.data, form.complexity.data, form.quality.data, form.delay.data , form.filler.data, form.URL_completion_code.data)
            db.session.add(t)
            db.session.commit()
            flash('task was created Successfully!')
            return redirect(url_for('main.prolific_admin'))

    tasks_ = TASK.query.order_by(asc(TASK.id)).all()
    number_of_workers = []
    # for t in tasks_:
    #     number_of_workers.append(db.session.query(SURVEY).filter(SURVEY.t_id == t.id).count())
    # print(number_of_workers)

    return render_template("prolific_admin.html", form = form, tasks = TASK.query.order_by(asc(TASK.id)).all(), \
    count = db.session.query(TASK).count(), number_of_workers=number_of_workers)


@main.route('/edit_task/<task_id>', methods=['GET', 'POST'])
# @login_required
def edit_task(task_id):

app/main/templates/IR-task.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
  crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
  crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <title></title>

  <style>
    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      max-width: 100%;
      margin: auto;
      padding: 40px;
      text-align: center;
      font-family: arial;
      background: whitesmoke;
    }

    .title {
      color: grey;
      font-size: 18px;
    }
  </style>
</head>

<body>
  <form method="post">
  <div class="container">

    <nav class="navbar navbar-light bg-light">

      <div class="text-center">
        <img src="/static/img/tue.png" width="20%" height="20%" class="mx-auto d-block" alt="">
        <h4>INSTRUCTIONS</h4>
      </div>
    </nav>
    <br>
    <div class="alert alert-dark" role="alert">
      <p>In the next page, the crowd-powered chatbot will provide you the following three types of search tasks as options to choose from. After you choose the category, a search task will be created and diplayed in the text field automatically. You can then read and send the text without editing. You do not have to create the search task yourself in this study.</p>

      <p>While waiting for the response, please do not switch tabs or do other tasks. Once you receive the response, read it carefully and then follow the next instructions from the chatbot.</p>

      <!-- <p>Once you load the chatbot in the next page, it will send you a greeting response, which is pre-programed and does not involve any crowd-powered support. However, the subsequent responses from the chatbot involve real time support from both humans and computation as explained in the consent form.</p> -->


    </div>
    <!-- COMPLEX CASE -->
    <div class="card" id="complex_case">
      <div class="card-header">
        <h5 class="card-title"><b>Search Tasks</b></h5>
      </div>
      <div class="card-body">

        <!-- card # 1 -->

        <div class="card mb-3">
          <div class="text-center">
            <img src="{{url_for('static', filename='img/health2.png')}}" class="rounded-circle" alt="Cinque Terre" width="75px">

          </div>
          <div class="card-body">
            <h2 class="card-title">Health</h2>
            <p class="card-text">My great granny's doctor has told her that getting more exercise will increase her fitness and help her avoid injuries. I need an exercise program for her. She is 90-years old. Help me to put together two thirty-minute low impact exercise
              programs that she could alternate between during the week.</p>
            <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          </div>
        </div>

        <!-- card # 2 -->

        <div class="card mb-3">
          <div class="text-center">
            <img src="{{url_for('static', filename='img/science.png')}}" class="rounded-circle" alt="Cinque Terre" width="75px">

          </div>
          <div class="card-body">
            <h2 class="card-title">Science & Technology</h2>
            <p class="card-text">After the NASCAR season opened this year, my niece became really interested in soapbox derby racing. Since her parents are both really busy, I agreed to help her build a car so that she can enter a local race. The first step is to figure out
              how to build a car. Identify some basic designs that you might use and help me to create a basic plan for constructing the car.</p>
            <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          </div>
        </div>

        <!-- card # 3 -->

        <div class="card mb-3">
          <div class="text-center">
            <img src="{{url_for('static', filename='img/entertainment.png')}}" class="rounded-circle" alt="Cinque Terre" width="75px">
          </div>
          <div class="card-body">
            <h2 class="card-title">Entertainment</h2>
            <p class="card-text">My local Triple-A affiliate baseball team has decided that it is time for a new mascot and are holding a contest where fans can enter suggestions. Being a loyal fan, I have decided to enter the contest. I want to suggest a mascot that will
              appeal to many people and will represent important qualities of a baseball team. The team is a part of the International League, so I want to avoid suggesting a mascot that is already represented in this league. Which mascot would I pick
              and why?</p>
            <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          </div>
        </div>
      </div>

    </div>

    <div class="card" id="simple_case">
      <div class="card-header">
        <h5 class="card-title"><b>Search Tasks</b></h5>
      </div>
      <div class="card-body">

        <!-- card # 1 -->

        <div class="card mb-3">
          <div class="text-center">
            <img src="{{url_for('static', filename='img/health2.png')}}" class="rounded-circle" alt="Cinque Terre" width="75px">

          </div>
          <div class="card-body">
            <h2 class="card-title">Health</h2>
            <p class="card-text">I recently watched a documentary about people living with HIV in the United States.
              I thought the disease was nearly eradicated, and am now curious to know more about the prevalence of the disease.
              Specifically, how many people in the US are currently living with HIV?</p>
            <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          </div>
        </div>

        <!-- card # 2 -->

        <div class="card mb-3">
          <div class="text-center">
            <img src="{{url_for('static', filename='img/science.png')}}" class="rounded-circle" alt="Cinque Terre" width="75px">

          </div>
          <div class="card-body">
            <h2 class="card-title">Science & Technology</h2>
            <p class="card-text">I recently watched a show on the Discovery Channel, about fish that can live so deep in the ocean that they're in darkness most or all of the time. This made me more curious about the deepest point in the ocean. What is the name of the deepest point in the ocean?</p>
            <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          </div>
        </div>

        <!-- card # 3 -->

        <div class="card mb-3">
          <div class="text-center">
            <img src="{{url_for('static', filename='img/entertainment.png')}}" class="rounded-circle" alt="Cinque Terre" width="75px">
          </div>
          <div class="card-body">
            <h2 class="card-title">Entertainment</h2>
            <p class="card-text">I recently attended an outdoor music festival and heard a band called Wolf Parade. I really enjoyed the band and want to purchase their latest album. What is the name of their latest (full-length) album?</p>
            <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p> -->
          </div>
        </div>
      </div>

    </div>

  </div>


<input type="hidden" id="hidden_field_IR" name="hidden_field_IR" value="3487">
  <br>
  <div class="text-center">
    <button type="submit" class="btn btn-secondary btn-lg" id="nextbtn">Proceed Further</button>
  </div>

</form>

  <script>
    function gup(name) {
      name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
      var regexS = "[\\?&]" + name + "=([^&#]*)";
      var regex = new RegExp(regexS);
      var results = regex.exec(window.location.href);
      if (results == null)
        return "";
      else
        return unescape(results[1]);
    }

    $(document).ready(function() {
      if (gup("c") == "1") $('#simple_case').hide();
      if (gup("c") == "0") $('#complex_case').hide();

      $.ajax({
              type: "POST",
              url: "/setTime",
              data: JSON.stringify({
                "nothing": {}
              }),
              contentType: "application/json; charset=utf-8",
              dataType: "json",
              success: function(data) {
              console.log(JSON.stringify(data));
              }
          });
    });

    $('#nextbtn').click(function() {
      var qs = {
        'workerId': gup("workerId"),
        'mood': gup("mood"),
        'context': gup("context"),
        'q': gup('q'),
        'c':gup('c'),
        'd':gup('d'),
        'ft': gup('ft')
      };
      window.location.replace("https://filler1.herokuapp.com/bot" + "?" + $.param(qs));
    });
  </script>
</body>

</html>

app/main/templates/edit.html
{% extends 'layout_admin.html' %}
{% block content %}
<!-- {{ form.hidden_tag() }}
    <div> {{ wtf.quick_form(form) }} </div> -->

    <form class="form form-horizontal" method="post" role="form">
  {{ form.hidden_tag() }}
  <!-- {{ form.csrf_token }} -->
  {{ wtf.form_errors(form, hiddens="only") }}

  {{ wtf.form_field(form.title) }}
  <h4>context</h4>
  {{ wtf.form_field(form.context) }}

  <h4>Complexity</h4>
  {{ wtf.form_field(form.complexity) }}

  <h4>Quality</h4>
  {{ wtf.form_field(form.quality) }}

  <h4>Filler</h4>
  {{ wtf.form_field(form.filler) }}

  <h4>Delay</h4>
  {{ wtf.form_field(form.delay) }}

  <h4>URL</h4>
  {{ wtf.form_field(form.url) }}

<br>
<div class="text-center">
    {{ wtf.form_field(form.submit) }}
</div>


</form>
{% endblock %}

app/main/templates/list-tasks.html
{% extends 'layout_surveys.html' %} {% block content %}

<h4>Total tasks: {{count}}</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Task ID</th>
      <th scope="col">Filler Type</th>
      <th scope="col">Icon</th>

      <th scope="col">Title</th>
      <th scope="col">Context</th>
      <!-- <th scope="col">Complexity</th>
            <th scope="col">Quality</th> -->
      <th scope="col">Delay</th>
      <th scope="col">URL</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr>
      <td> {{task.id }} </td>
      {%if task.filler_type == 'CF' %}
      <td>Conversational filler</td>
      {% else %}
      <td>{{ task.filler_type }}</td>
      {% endif %}

      {%if task.filler_type == 'CF' %}
      <td> <i class="far fa-comment-dots"></i> </td>
      {% elif task.filler_type == 'dots' %}
      <td> <i class="fas fa-ellipsis-h"></i></td>
      {% elif task.filler_type == 'progress' %}
      <td> <i class="fas fa-spinner"></i></td>
      {% elif task.filler_type == 'nature' %}
      <td> <i class="fas fa-leaf"></i> </td>
      {% elif task.filler_type == 'manmade' %}
      <td> <i class="fas fa-building"></i> </td>
      {% elif task.filler_type == 'micro' %}
      <td> <i class="fas fa-tasks"></i></td>
      {% elif task.filler_type == 'box' %}
      <td> <i class="fas fa-lungs"></i></td>
      {% else %}
      <td> <i class="fab fa-creative-commons-zero"></i></td>
      {% endif %}


      <td> {{ task.title }} </td>
      <td>{{task.context}}</td>
      <!-- {%if task.complexity == '1' %}
            <td>HIGH</td>
            {% else %}
            <td>LOW</td>
            {% endif %}
            {%if task.quality == '1' %}
            <td>HIGH</td>
            {% else %}
            <td>LOW</td>
            {% endif %} -->

      {%if task.delay == '2' %}
      <td>2-sec</td>
      {% elif task.delay == '4' %}
      <td>4-sec</td>
      {% elif task.delay == '8' %}
      <td>8-sec</td>
      {% elif task.delay == '12' %}
      <td>12-sec</td>
      {% else %}
      <td>16-sec</td>
      {% endif %}
      <td> <a href="https://filler1.herokuapp.com/consent?context={{task.context}}&c={{task.complexity }}&q={{task.quality }}&d={{task.delay }}&ft={{ task.filler_type }}">https://filler1.herokuapp.com/consent?context={{task.context}}&c={{task.complexity }}&q={{task.quality }}&d={{task.delay }}&ft={{ task.filler_type }}</a>        </td>

    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

app/main/templates/prolific_admin.html
{% extends 'layout_admin.html' %} {% block content %}

<form action="" method="post" novalidate>

  <h4 style="margin-left: 45px"> create a new Task </h4>
  <hr> {{ form.hidden_tag() }}
  <!-- {{ form.csrf_token }} -->
  <!-- {{ wtf.quick_form(form) }} -->

  <p>{{form.title.label}}: {{form.title(size=100)}} {% for error in form.title.errors %}
    <span style="color: red;">[{{ error }}]</span> {% endfor %}</p>


  <table>
    <tr>
      <td>{{form.context.label}} {% for error in form.context.errors %}
        <span style="color: red;">[{{ error }}]</span> {% endfor %}</td>
      {% for radiobutton in form.context %}
      <td style="padding: 20px;">
        {{ radiobutton }} {{ radiobutton.label }}
      </td>
      {% endfor %}
    </tr>

  </table>


  <table>
    <tr class="complexity">
      <td>{{form.complexity.label}} {% for error in form.complexity.errors %}
        <span style="color: red;">[{{ error }}]</span> {% endfor %}</td>
      {% for radiobutton in form.complexity %}
      <td style="padding: 20px;">
        {{ radiobutton }} {{ radiobutton.label }}
      </td>
      {% endfor %}
    </tr>

  </table>


  <table>
    <tr class="quality">
      <td>{{form.quality.label}} {% for error in form.quality.errors %}
        <span style="color: red;">[{{ error }}]</span> {% endfor %}</td>
      {% for radiobutton in form.quality %}
      <td style="padding: 20px;">
        {{ radiobutton }} {{ radiobutton.label }}
      </td>
      {% endfor %}
    </tr>

  </table>


  <table>
    <tr>
      <td>{{form.filler.label}} {% for error in form.filler.errors %}
        <span style="color: red;">[{{ error }}]</span> {% endfor %}</td>
      {% for radiobutton in form.filler %}
      <td style="padding: 20px;">
        {{ radiobutton }} {{ radiobutton.label }}
      </td>
      {% endfor %}
    </tr>

  </table>

  <table>
    <tr>
      <td>{{form.delay.label}} {% for error in form.delay.errors %}
        <span style="color: red;">[{{ error }}]</span> {% endfor %}</td>
      {% for radiobutton in form.delay %}
      <td style="padding: 20px;">
        {{ radiobutton }} {{ radiobutton.label }}
      </td>
      {% endfor %}
    </tr>

  </table>




  <p>{{form.URL_completion_code.label}}: {{form.URL_completion_code(size=100)}} {% for error in form.URL_completion_code.errors %}
    <span style="color: red;">[{{ error }}]</span> {% endfor %}</p>
  <div class="row">
    <div class="col-lg-4">

    </div>
    <div class="col-lg-4">
      <br> {{ form.submit() }}
    </div>
    <div class="col-lg-4">

    </div>

  </div>

</form>
<br><br>

<h4>TOTAL ENTREIS: {{count}}</h4>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Task ID</th>
      <th scope="col">Title</th>
      <th scope="col">Context</th>
      <th scope="col">Complexity</th>
      <th scope="col">Quality</th>
      <th scope="col">Delay</th>
      <th scope="col">Filler Type</th>
      <th scope="col">Competion URL</th>
      <th scope="col">URL</th>
      <th scope="col">Total Workers</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr>
      <td> {{task.id }} </td>
      <td> {{ task.title }} </td>
      <td>{{task.context}}</td>
      <!-- {%if task.context == '1' %}
                  <td>STRESS</td>
                  {% else %}
                  <td>IR</td>
                  {% endif %} -->

      {%if task.complexity == '1' %}
      <td>HIGH</td>
      {% else %}
      <td>LOW</td>
      {% endif %}
      <!-- <td> {{ task.context }}</td> -->
      <!-- <td> {{ task.complexity }}</td> -->

      {%if task.quality == '1' %}
      <td>HIGH</td>
      {% else %}
      <td>LOW</td>
      {% endif %}
      <!-- <td> {{ task.quality }}</td> -->

      {%if task.delay == '8' %}
      <td>8-sec</td>
      {% elif task.delay == '16' %}
      <td>16-sec</td>
      {% else %}
      <td>32-sec</td>
      {% endif %}

      <td> {{ task.filler_type }} </td>

      <!-- <td> {{ task.delay }}</td> -->
      <td> {{ task.URL_completion_code }} </td>
      <td> <a href="https://filler1.herokuapp.com/consent?context={{task.context}}&c={{task.complexity }}&q={{task.quality }}&d={{task.delay }}&ft={{task.filler_type }}">https://filler1.herokuapp.com/consent?context={{task.context}}&c={{task.complexity }}&q={{task.quality }}&d={{task.delay }}&ft={{task.filler_type }}</a>        </td>
      <td>{{number_of_workers[loop.index-1]}}</td>
      <td> <a href="{{ url_for('main.edit_task', task_id=task.id)}}"> Edit </a></td>

    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}